import type { ExerciseCategory, ExerciseRole, LiftFamily } from '@/src/domain/types';
import generateId from '@/src/lib/uuid';

import type { PowerLogDatabase } from './types';

interface ExerciseSeed {
  nameEn: string;
  nameZh: string;
  category: ExerciseCategory;
  liftFamily: LiftFamily;
  role: ExerciseRole;
  muscleGroups: string[];
  equipment: string;
}

export const EXERCISE_SEEDS: ExerciseSeed[] = [
  {
    nameEn: 'Squat',
    nameZh: '深蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'competition',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Bench Press',
    nameZh: '卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'competition',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Deadlift',
    nameZh: '硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'competition',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Overhead Press',
    nameZh: '站姿推举',
    category: 'barbell',
    liftFamily: 'upper',
    role: 'variation',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Barbell Row',
    nameZh: '杠铃划船',
    category: 'barbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Lat Pulldown',
    nameZh: '高位下拉',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['lats', 'biceps'],
    equipment: 'cable',
  },
  {
    nameEn: 'Leg Press',
    nameZh: '腿举',
    category: 'machine',
    liftFamily: 'squat',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'machine',
  },
  {
    nameEn: 'Leg Curl',
    nameZh: '腿弯举',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['hamstrings'],
    equipment: 'machine',
  },
  {
    nameEn: 'Leg Extension',
    nameZh: '腿屈伸',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['quads'],
    equipment: 'machine',
  },
  {
    nameEn: 'Triceps Pushdown',
    nameZh: '绳索下压',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['triceps'],
    equipment: 'cable',
  },
  {
    nameEn: 'Lateral Raise',
    nameZh: '侧平举',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['side_delt'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Pull-Up',
    nameZh: '引体向上',
    category: 'bodyweight',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['lats', 'biceps'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Chin-Up',
    nameZh: '反手引体向上',
    category: 'bodyweight',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['lats', 'biceps'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Push-Up',
    nameZh: '俯卧撑',
    category: 'bodyweight',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['chest', 'triceps', 'front_delt', 'core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Dumbbell Row',
    nameZh: '哑铃划船',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Romanian Deadlift',
    nameZh: '罗马尼亚硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Biceps Curl',
    nameZh: '二头弯举',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Face Pull',
    nameZh: '面拉',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['rear_delt', 'upper_back'],
    equipment: 'cable',
  },
  {
    nameEn: 'Hack Squat',
    nameZh: '哈克深蹲',
    category: 'machine',
    liftFamily: 'squat',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'machine',
  },
  {
    nameEn: 'Close Grip Bench',
    nameZh: '窄距卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['triceps', 'chest'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Incline Bench Press',
    nameZh: '上斜卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['upper_chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Bulgarian Split Squat',
    nameZh: '保加利亚分腿蹲',
    category: 'dumbbell',
    liftFamily: 'squat',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Pause Squat',
    nameZh: '暂停深蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'variation',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Tempo Squat',
    nameZh: '节奏深蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'variation',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Pause Deadlift',
    nameZh: '暂停硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Deficit Deadlift',
    nameZh: '垫高硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Block Pull',
    nameZh: '架上硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Paused Bench Press',
    nameZh: '暂停卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Spoto Press',
    nameZh: '斯波托卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Dumbbell Bench Press',
    nameZh: '哑铃卧推',
    category: 'dumbbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Incline Dumbbell Bench Press',
    nameZh: '上斜哑铃卧推',
    category: 'dumbbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['upper_chest', 'triceps', 'front_delt'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Dumbbell Shoulder Press',
    nameZh: '哑铃肩推',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Seated Dumbbell Shoulder Press',
    nameZh: '坐姿哑铃肩推',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Dumbbell Fly',
    nameZh: '哑铃飞鸟',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['chest'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Incline Dumbbell Fly',
    nameZh: '上斜哑铃飞鸟',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['upper_chest', 'chest'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Dumbbell Pullover',
    nameZh: '哑铃上拉',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['chest', 'lats'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Goblet Squat',
    nameZh: '高脚杯深蹲',
    category: 'dumbbell',
    liftFamily: 'squat',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Dumbbell Romanian Deadlift',
    nameZh: '哑铃罗马尼亚硬拉',
    category: 'dumbbell',
    liftFamily: 'deadlift',
    role: 'accessory',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Walking Lunge',
    nameZh: '行走弓步',
    category: 'dumbbell',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Hammer Curl',
    nameZh: '锤式弯举',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['biceps', 'forearms'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Front Raise',
    nameZh: '前平举',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['front_delt'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Chest Press Machine',
    nameZh: '坐姿推胸机',
    category: 'machine',
    liftFamily: 'bench',
    role: 'accessory',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'machine',
  },
  {
    nameEn: 'Machine Shoulder Press',
    nameZh: '器械肩推',
    category: 'machine',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'machine',
  },
  {
    nameEn: 'Chest Supported Row',
    nameZh: '胸托划船',
    category: 'machine',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'machine',
  },
  {
    nameEn: 'Seated Cable Row',
    nameZh: '坐姿绳索划船',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable',
  },
  {
    nameEn: 'Single Arm Triceps Extension',
    nameZh: '单臂三头伸展',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['triceps'],
    equipment: 'cable',
  },
  {
    nameEn: 'Overhead Triceps Extension',
    nameZh: '过顶臂屈伸',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['triceps'],
    equipment: 'cable',
  },
  {
    nameEn: 'Cable Fly',
    nameZh: '绳索飞鸟',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['chest'],
    equipment: 'cable',
  },
  {
    nameEn: 'Rear Delt Fly',
    nameZh: '后束飞鸟',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['rear_delt', 'upper_back'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Calf Raise',
    nameZh: '提踵',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['calves'],
    equipment: 'machine',
  },
  {
    nameEn: 'Standing Calf Raise',
    nameZh: '站姿提踵',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['calves'],
    equipment: 'machine',
  },
  {
    nameEn: 'Seated Calf Raise',
    nameZh: '坐姿提踵',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['calves'],
    equipment: 'machine',
  },
  {
    nameEn: 'Back Extension',
    nameZh: '背伸',
    category: 'bodyweight',
    liftFamily: 'deadlift',
    role: 'accessory',
    muscleGroups: ['lower_back', 'glutes', 'hamstrings'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Hyperextension',
    nameZh: '山羊挺身',
    category: 'bodyweight',
    liftFamily: 'deadlift',
    role: 'accessory',
    muscleGroups: ['lower_back', 'glutes', 'hamstrings'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Reverse Hyperextension',
    nameZh: '反向山羊挺身',
    category: 'machine',
    liftFamily: 'deadlift',
    role: 'accessory',
    muscleGroups: ['glutes', 'hamstrings', 'lower_back'],
    equipment: 'machine',
  },
  {
    nameEn: 'Plank',
    nameZh: '平板支撑',
    category: 'bodyweight',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Ab Wheel',
    nameZh: '健腹轮',
    category: 'bodyweight',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Hip Thrust',
    nameZh: '臀推',
    category: 'barbell',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Pec Fly',
    nameZh: '夹胸飞鸟',
    category: 'machine',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['chest'],
    equipment: 'machine',
  },
  {
    nameEn: 'Hanging Leg Raise',
    nameZh: '悬垂举腿',
    category: 'bodyweight',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Hanging Knee Raise',
    nameZh: '悬垂举膝',
    category: 'bodyweight',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core', 'hip_flexors'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Cable Crunch',
    nameZh: '绳索卷腹',
    category: 'cable',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'cable',
  },
  {
    nameEn: 'Decline Sit-Up',
    nameZh: '下斜仰卧起坐',
    category: 'bodyweight',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'T-Bar Row',
    nameZh: 'T杠划船',
    category: 'machine',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'machine',
  },
  {
    nameEn: 'Adductor Machine',
    nameZh: '内收肌训练器',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['adductors'],
    equipment: 'machine',
  },
  {
    nameEn: 'Back Squat',
    nameZh: '背蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'competition',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipment: 'barbell',
  },
  {
    nameEn: 'High Bar Squat',
    nameZh: '高杠深蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'variation',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Low Bar Squat',
    nameZh: '低杠深蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'variation',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Safety Bar Squat',
    nameZh: '安全杠深蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'variation',
    muscleGroups: ['quads', 'glutes', 'upper_back'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Front Squat',
    nameZh: '前蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'variation',
    muscleGroups: ['quads', 'core'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Pin Squat',
    nameZh: '插销蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'variation',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Box Squat',
    nameZh: '箱式深蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'variation',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Belt Squat',
    nameZh: '腰带深蹲',
    category: 'machine',
    liftFamily: 'squat',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'machine',
  },
  {
    nameEn: 'Close-Grip Bench Press',
    nameZh: '窄距卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Pause Bench Press',
    nameZh: '暂停卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Tempo Bench Press',
    nameZh: '节奏卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Larsen Press',
    nameZh: '抬腿卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Incline Barbell Bench Press',
    nameZh: '上斜杠铃卧推',
    category: 'barbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['chest', 'front_delt', 'triceps'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Incline Dumbbell Press',
    nameZh: '上斜哑铃卧推',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['chest', 'front_delt', 'triceps'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Push Press',
    nameZh: '借力推举',
    category: 'barbell',
    liftFamily: 'upper',
    role: 'variation',
    muscleGroups: ['shoulders', 'triceps', 'quads'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Dip',
    nameZh: '双杠臂屈伸',
    category: 'bodyweight',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Conventional Deadlift',
    nameZh: '传统硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'competition',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Sumo Deadlift',
    nameZh: '相扑硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'competition',
    muscleGroups: ['glutes', 'quads', 'back'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Stiff-Leg Deadlift',
    nameZh: '直腿硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Rack Pull',
    nameZh: '架上拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['back', 'glutes'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Trap Bar Deadlift',
    nameZh: '六角杠硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['quads', 'glutes', 'back'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Good Morning',
    nameZh: '早安体前屈',
    category: 'barbell',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['hamstrings', 'glutes', 'lower_back'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Glute Bridge',
    nameZh: '臀桥',
    category: 'barbell',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Assisted Pull-up',
    nameZh: '辅助引体向上',
    category: 'machine',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['lats', 'biceps'],
    equipment: 'machine',
  },
  {
    nameEn: 'Pendlay Row',
    nameZh: '彭德雷划船',
    category: 'barbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Split Squat',
    nameZh: '分腿蹲',
    category: 'dumbbell',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Reverse Lunge',
    nameZh: '后撤步弓步',
    category: 'dumbbell',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Seated Leg Curl',
    nameZh: '坐姿腿弯举',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['hamstrings'],
    equipment: 'machine',
  },
  {
    nameEn: 'Lying Leg Curl',
    nameZh: '俯卧腿弯举',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['hamstrings'],
    equipment: 'machine',
  },
  {
    nameEn: 'Copenhagen Plank',
    nameZh: '哥本哈根平板',
    category: 'bodyweight',
    liftFamily: 'core',
    role: 'accessory',
    muscleGroups: ['adductors', 'core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Barbell Curl',
    nameZh: '杠铃弯举',
    category: 'barbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['biceps'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Dumbbell Curl',
    nameZh: '哑铃弯举',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Skull Crusher',
    nameZh: '碎颅式三头',
    category: 'barbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['triceps'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Cable Lateral Raise',
    nameZh: '绳索侧平举',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['side_delt'],
    equipment: 'cable',
  },
  {
    nameEn: 'Side Plank',
    nameZh: '侧平板支撑',
    category: 'bodyweight',
    liftFamily: 'core',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Pallof Press',
    nameZh: '帕洛夫推',
    category: 'cable',
    liftFamily: 'core',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'cable',
  },
  {
    nameEn: 'Dead Bug',
    nameZh: '死虫',
    category: 'bodyweight',
    liftFamily: 'core',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
  },
];

export const seedExercises = async (db: PowerLogDatabase): Promise<void> => {
  let inserted = 0;
  let skipped = 0;
  for (const exercise of EXERCISE_SEEDS) {
    const existing = await db.getFirstAsync<{ id: string }>('SELECT id FROM exercises WHERE lower(name_en) = lower(?) LIMIT 1', [
      exercise.nameEn,
    ]);

    if (existing) {
      skipped++;
      continue;
    }

    await db.runAsync(
      `INSERT INTO exercises (
        id,
        name_en,
        name_zh,
        category,
        lift_family,
        role,
        muscle_groups,
        equipment,
        is_custom
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        generateId(),
        exercise.nameEn,
        exercise.nameZh,
        exercise.category,
        exercise.liftFamily,
        exercise.role,
        JSON.stringify(exercise.muscleGroups),
        exercise.equipment,
        0,
      ],
    );
    inserted++;
  }
  console.log(`[exerciseSeed] total canonical exercises: ${EXERCISE_SEEDS.length}, inserted: ${inserted}, skipped: ${skipped}`);
};
