import type { ExerciseCategory, ExerciseRole, LiftFamily } from '@/src/domain/types';
import generateId from '@/src/lib/uuid';

import type { PowerLogDatabase } from './types';

interface ExerciseSeed {
  nameEn: string;
  nameZh: string;
  category: ExerciseCategory;
  liftFamily: LiftFamily;
  role: ExerciseRole;
  muscleGroups: string[];
  equipment: string;
}

export const EXERCISE_SEEDS: ExerciseSeed[] = [
  {
    nameEn: 'Squat',
    nameZh: '深蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'competition',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Bench Press',
    nameZh: '卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'competition',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Deadlift',
    nameZh: '硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'competition',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Overhead Press',
    nameZh: '站姿推举',
    category: 'barbell',
    liftFamily: 'upper',
    role: 'variation',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Barbell Row',
    nameZh: '杠铃划船',
    category: 'barbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Lat Pulldown',
    nameZh: '高位下拉',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['lats', 'biceps'],
    equipment: 'cable',
  },
  {
    nameEn: 'Leg Press',
    nameZh: '腿举',
    category: 'machine',
    liftFamily: 'squat',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'machine',
  },
  {
    nameEn: 'Leg Curl',
    nameZh: '腿弯举',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['hamstrings'],
    equipment: 'machine',
  },
  {
    nameEn: 'Leg Extension',
    nameZh: '腿屈伸',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['quads'],
    equipment: 'machine',
  },
  {
    nameEn: 'Triceps Pushdown',
    nameZh: '绳索下压',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['triceps'],
    equipment: 'cable',
  },
  {
    nameEn: 'Lateral Raise',
    nameZh: '侧平举',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['side_delt'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Pull-Up',
    nameZh: '引体向上',
    category: 'bodyweight',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['lats', 'biceps'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Dumbbell Row',
    nameZh: '哑铃划船',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Romanian Deadlift',
    nameZh: '罗马尼亚硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['hamstrings', 'glutes', 'back'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Biceps Curl',
    nameZh: '二头弯举',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['biceps'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Face Pull',
    nameZh: '面拉',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['rear_delt', 'upper_back'],
    equipment: 'cable',
  },
  {
    nameEn: 'Hack Squat',
    nameZh: '哈克深蹲',
    category: 'machine',
    liftFamily: 'squat',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'machine',
  },
  {
    nameEn: 'Close Grip Bench',
    nameZh: '窄距卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['triceps', 'chest'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Incline Bench Press',
    nameZh: '上斜卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['upper_chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Bulgarian Split Squat',
    nameZh: '保加利亚分腿蹲',
    category: 'dumbbell',
    liftFamily: 'squat',
    role: 'accessory',
    muscleGroups: ['quads', 'glutes'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Pause Squat',
    nameZh: '暂停深蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'variation',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Tempo Squat',
    nameZh: '节奏深蹲',
    category: 'barbell',
    liftFamily: 'squat',
    role: 'variation',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Pause Deadlift',
    nameZh: '暂停硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Deficit Deadlift',
    nameZh: '垫高硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Block Pull',
    nameZh: '架上硬拉',
    category: 'barbell',
    liftFamily: 'deadlift',
    role: 'variation',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Paused Bench Press',
    nameZh: '暂停卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Spoto Press',
    nameZh: '斯波托卧推',
    category: 'barbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Dumbbell Bench Press',
    nameZh: '哑铃卧推',
    category: 'dumbbell',
    liftFamily: 'bench',
    role: 'variation',
    muscleGroups: ['chest', 'triceps', 'front_delt'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Chest Supported Row',
    nameZh: '胸托划船',
    category: 'machine',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'machine',
  },
  {
    nameEn: 'Seated Cable Row',
    nameZh: '坐姿绳索划船',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'cable',
  },
  {
    nameEn: 'Single Arm Triceps Extension',
    nameZh: '单臂三头伸展',
    category: 'cable',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['triceps'],
    equipment: 'cable',
  },
  {
    nameEn: 'Rear Delt Fly',
    nameZh: '后束飞鸟',
    category: 'dumbbell',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['rear_delt', 'upper_back'],
    equipment: 'dumbbell',
  },
  {
    nameEn: 'Calf Raise',
    nameZh: '提踵',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['calves'],
    equipment: 'machine',
  },
  {
    nameEn: 'Back Extension',
    nameZh: '背伸',
    category: 'bodyweight',
    liftFamily: 'deadlift',
    role: 'accessory',
    muscleGroups: ['lower_back', 'glutes', 'hamstrings'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Plank',
    nameZh: '平板支撑',
    category: 'bodyweight',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Ab Wheel',
    nameZh: '健腹轮',
    category: 'bodyweight',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Hip Thrust',
    nameZh: '臀推',
    category: 'barbell',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: 'barbell',
  },
  {
    nameEn: 'Pec Fly',
    nameZh: '夹胸飞鸟',
    category: 'machine',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['chest'],
    equipment: 'machine',
  },
  {
    nameEn: 'Hanging Leg Raise',
    nameZh: '悬垂举腿',
    category: 'bodyweight',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'Cable Crunch',
    nameZh: '绳索卷腹',
    category: 'cable',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'cable',
  },
  {
    nameEn: 'Decline Sit-Up',
    nameZh: '下斜仰卧起坐',
    category: 'bodyweight',
    liftFamily: 'accessory',
    role: 'accessory',
    muscleGroups: ['core'],
    equipment: 'bodyweight',
  },
  {
    nameEn: 'T-Bar Row',
    nameZh: 'T杠划船',
    category: 'machine',
    liftFamily: 'upper',
    role: 'accessory',
    muscleGroups: ['back', 'biceps'],
    equipment: 'machine',
  },
  {
    nameEn: 'Adductor Machine',
    nameZh: '内收肌训练器',
    category: 'machine',
    liftFamily: 'lower',
    role: 'accessory',
    muscleGroups: ['adductors'],
    equipment: 'machine',
  },
];

export const seedExercises = async (db: PowerLogDatabase): Promise<void> => {
  for (const exercise of EXERCISE_SEEDS) {
    const existing = await db.getFirstAsync<{ id: string }>('SELECT id FROM exercises WHERE lower(name_en) = lower(?) LIMIT 1', [
      exercise.nameEn,
    ]);

    if (existing) {
      continue;
    }

    await db.runAsync(
      `INSERT INTO exercises (
        id,
        name_en,
        name_zh,
        category,
        lift_family,
        role,
        muscle_groups,
        equipment,
        is_custom
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        generateId(),
        exercise.nameEn,
        exercise.nameZh,
        exercise.category,
        exercise.liftFamily,
        exercise.role,
        JSON.stringify(exercise.muscleGroups),
        exercise.equipment,
        0,
      ],
    );
  }
};
