import type { ChatMessage } from '../services/deepseek';

export const buildPlanParsePrompt = (data: {
  planText: string;
}): ChatMessage[] => [
  {
    role: 'system',
    content: `You are an expert strength coach and training plan parser.
Your job is to read a free-text training plan (generated by another AI or written by a human) and convert it into a structured JSON format.

The input text describes a training program with weeks, days, exercises, sets, reps, and optionally RPE/percentages.

Return a JSON object with this EXACT structure:
{
  "name": "Program name (derived from the text, or 'Imported Plan')",
  "type": "strength|hypertrophy|powerbuilding|maintenance",
  "description": "Brief 1-2 sentence summary of the program",
  "weeks": [
    {
      "weekNumber": 1,
      "phase": "entry|accumulation|intensification|deload|peak|test|maintenance",
      "focus": "Brief focus for this week",
      "days": [
        {
          "dayNumber": 1,
          "title": "Day title (e.g. Squat Focus + Bench Volume)",
          "mainFocus": "squat|bench|deadlift|upper|lower",
          "estimatedDuration": 90,
          "exercises": [
            {
              "exerciseNameEn": "Competition Squat",
              "role": "competition|variation|accessory",
              "targetSets": 4,
              "targetReps": 5,
              "targetRpe": 7.5,
              "targetPercent": null,
              "notes": "Top set + back-offs"
            }
          ]
        }
      ]
    }
  ]
}

Rules:
- Use the EXACT exercise names from the text (English names). Do NOT invent new names.
- Infer program type from the text content (heavy triples → strength, high volume → hypertrophy, mixed → powerbuilding).
- Assign phases based on week content: early weeks with lower intensity → "entry", heavy weeks → "intensification", light weeks → "deload", peaking → "peak".
- Default estimatedDuration to 90 minutes unless specified.
- If sets x reps is written as "3x5", that means targetSets=3, targetReps=5.
- If RPE is specified (e.g. "@8", "RPE 8"), set targetRpe accordingly.
- If percentage is specified (e.g. "80%", "85% 1RM"), set targetPercent accordingly.
- If the text mentions warm-up sets, ignore them — only include working sets.
- Exercise role: "competition" for squat/bench/deadlift/OHS, "variation" for pause/spoto/tempo/front squat variants, "accessory" for everything else.
- If the text doesn't specify a program name, use a descriptive name based on the content.`
  },
  {
    role: 'user',
    content: `Parse this training plan into the structured JSON format:

${data.planText}`
  },
];
